version: '3.8'

services:
  db:
    container_name: spa-app-db-prod
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
  server:
    container_name: spa-app-server-prod
    build:
      dockerfile: docker/server.prod.Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_URL=${SERVER_URL}
      - UI_PORT=${UI_PORT}
      - UI_URL=${UI_URL}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_HOST=db
  ui:
    container_name: spa-app-ui-prod
    image: nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    build:
      context: .
      dockerfile: docker/ui.prod.Dockerfile
    ports:
      - ${UI_PORT}:${UI_PORT}
    depends_on:
      - db
      - server
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_URL=${SERVER_URL}
      - UI_PORT=${UI_PORT}
      - UI_URL=${UI_URL}
